sudo: required

language: node_js

node_js:
- "node"
- "8"

services:
  - docker

install:
  - npm install

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d

script:
  - jest --coverage --coverageReporters=text-lcov | coveralls