version: "3"

services: 
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"